/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

import org.example.model.DataBaseConnexion;
import org.example.model.Room;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.util.Map;

/**
 *
 * @author DELL
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    public AdminView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomsSideBar = new javax.swing.JPanel();
        createRoomButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        modifyRoomButton = new javax.swing.JButton();
        deleteRoomButton = new javax.swing.JButton();
        reservationsPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        JPanel container = new JPanel();
        container.setLayout(new BoxLayout(container, BoxLayout.Y_AXIS));

        for(Map.Entry<Integer, Room> entry : DataBaseConnexion.roomsMap.entrySet()) {
            RoomPanel roomPanel = new RoomPanel();
            roomPanel.addRoomNumber(entry.getValue().getRoomnumber());
            roomPanel.addRoomType(entry.getValue().getRoomtype());
            roomPanel.addRoomPrice(entry.getValue().getRoomprice());
            container.add(roomPanel);
        }
        reservationsPanel.setViewportView(container);

        createRoomButton.setText("Create Room");

        jLabel1.setText("Chhose your Action:");

        modifyRoomButton.setText("Modify Room");

        deleteRoomButton.setText("Delete Room");

        javax.swing.GroupLayout roomsSideBarLayout = new javax.swing.GroupLayout(roomsSideBar);
        roomsSideBar.setLayout(roomsSideBarLayout);
        roomsSideBarLayout.setHorizontalGroup(
            roomsSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomsSideBarLayout.createSequentialGroup()
                .addGroup(roomsSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomsSideBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomsSideBarLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(createRoomButton))
                    .addGroup(roomsSideBarLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(modifyRoomButton))
                    .addGroup(roomsSideBarLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(deleteRoomButton)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        roomsSideBarLayout.setVerticalGroup(
            roomsSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomsSideBarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modifyRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        reservationsPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roomsSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomsSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reservationsPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    public void onClickedCreateRoomView(ActionListener actionListener)
    {
        createRoomButton.addActionListener(actionListener);
    }
    public void onClickedModifyRoomView(ActionListener actionListener)
    {
        modifyRoomButton.addActionListener(actionListener);
    }
    public void onClickedDeleteRoomView(ActionListener actionListener)
    {
        deleteRoomButton.addActionListener(actionListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton createRoomButton;
    public javax.swing.JButton deleteRoomButton;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton modifyRoomButton;
    public javax.swing.JScrollPane reservationsPanel;
    private javax.swing.JPanel roomsSideBar;
    public CreateRoomView createRoomView;
    public ModifyRoomView modifyRoomView;
    public DeleteRoomView deleteRoomView;

    // End of variables declaration//GEN-END:variables
}
