/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

import org.example.model.DataBaseConnexion;
import org.example.model.Room;
import org.example.view.CreateRoomView;
import org.example.view.DeleteRoomView;
import org.example.view.ModifyRoomView;
import org.example.view.RoomPanel;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Map;

/**
 *
 * @author DELL
 */
public class ClientView extends JFrame {

   public ArrayList<RoomPanel> roomPanels = new ArrayList<>();
    public ClientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomsSideBar = new javax.swing.JPanel();
        viewReservationButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        reservationsPanel = new javax.swing.JScrollPane();
        JPanel container = new JPanel();
        container.setLayout(new BoxLayout(container, BoxLayout.Y_AXIS));

        for(Map.Entry<Integer, Room> entry : DataBaseConnexion.roomsMap.entrySet()) {
            RoomPanel roomPanel = new RoomPanel();
            roomPanel.addRoomNumber(entry.getValue().getRoomnumber());
            roomPanel.addRoomType(entry.getValue().getRoomtype());
            roomPanel.addRoomPrice(entry.getValue().getRoomprice());
            roomPanels.add(roomPanel);
            container.add(roomPanel);
        }
        reservationsPanel.setViewportView(container);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewReservationButton.setText("View Reservation");

        jLabel1.setText("Chose your Action:");

        logOutButton.setText("Logout");

        javax.swing.GroupLayout roomsSideBarLayout = new javax.swing.GroupLayout(roomsSideBar);
        roomsSideBar.setLayout(roomsSideBarLayout);
        roomsSideBarLayout.setHorizontalGroup(
            roomsSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomsSideBarLayout.createSequentialGroup()
                .addGroup(roomsSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roomsSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(roomsSideBarLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(roomsSideBarLayout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(viewReservationButton))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        roomsSideBarLayout.setVerticalGroup(
            roomsSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomsSideBarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        reservationsPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roomsSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomsSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reservationsPanel)
        );

        pack();
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents




    public void onClickedReservationButtonListener(ActionListener listener,int i){roomPanels.get(i).OnClickedReserveButton(listener);}
    public void onClickedViewReservationButton(ActionListener listener){viewReservationButton.addActionListener(listener);}
    public void onClickedLogOutButton(ActionListener listener){logOutButton.addActionListener(listener);}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JScrollPane reservationsPanel;
    private javax.swing.JPanel roomsSideBar;
    private javax.swing.JButton viewReservationButton;
    // End of variables declaration//GEN-END:variables

    //to put after reusing netbeans
//    JPanel container = new JPanel();
//        container.setLayout(new BoxLayout(container, BoxLayout.Y_AXIS));
//
//        for(Map.Entry<Integer, Room> entry : DataBaseConnexion.roomsMap.entrySet()) {
//        RoomPanel roomPanel = new RoomPanel();
//        roomPanel.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0));
//        roomPanel.addRoomNumber(entry.getValue().getRoomnumber());
//        roomPanel.addRoomType(entry.getValue().getRoomtype());
//        roomPanel.addRoomPrice(entry.getValue().getRoomprice());
//        container.add(roomPanel);
//    }
//        reservationsPanel.setViewportView(container);
}
